- hosts: apache
  become: True
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: installed
    - name: place index file on apache
      copy:
        src: index.html
        dest: /var/www/html
    - name: start apache
      service:
        name: httpd
        state: started
        enabled: True
